version: ""

services:
  api: 
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    ports: 
      - '8000:8000'
    volumes:
      - ./../app:/app

  redis_channels:
    image: redis
    ports:
      - 6379:6379