# Generated by Django 5.0.7 on 2024-07-12 21:53

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("board_points", models.CharField(max_length=200)),
                ("winner", models.CharField(default=None, max_length=20, null=True)),
                ("is_over", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GameSessionPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "game_session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tic_tac_toe.gamesession",
                    ),
                ),
            ],
        ),
    ]
