# Generated by Django 5.0.7 on 2024-07-13 00:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0003_gamesession_next_turn"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="status",
            field=models.CharField(default="WAITING_FOR_PLAYER", max_length=50),
        ),
    ]
