# Generated by Django 5.0.7 on 2024-07-13 00:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0004_gamesession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="game_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
