# Generated by Django 5.0.7 on 2024-07-13 14:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0005_gamesession_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessionplayer",
            name="is_host",
            field=models.BooleanField(default=False),
        ),
    ]
