# Generated by Django 5.0.7 on 2024-07-13 14:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0006_gamesessionplayer_is_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
