# Generated by Django 5.0.7 on 2024-07-13 17:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0007_alter_gamesession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesessionplayer",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
