# Generated by Django 5.0.7 on 2024-07-13 17:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0008_alter_gamesessionplayer_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gamesessionplayer",
            constraint=models.UniqueConstraint(
                fields=("id", "game_session_id"), name="game_session_player_id"
            ),
        ),
    ]
