# Generated by Django 5.0.7 on 2024-07-13 18:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0009_gamesessionplayer_game_session_player_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessionplayer",
            name="item",
            field=models.CharField(default="", max_length=5),
        ),
    ]
