# Generated by Django 5.0.7 on 2024-07-13 18:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0010_gamesessionplayer_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesessionplayer",
            name="item",
            field=models.CharField(max_length=5),
        ),
    ]
