# Generated by Django 5.0.7 on 2024-07-14 21:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0011_alter_gamesessionplayer_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="host",
            field=models.CharField(default="", max_length=20),
        ),
    ]
