# Generated by Django 5.0.7 on 2024-07-14 22:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tic_tac_toe", "0012_gamesession_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="host",
            field=models.CharField(max_length=20),
        ),
    ]
